// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMManagerApi.Models;

namespace TMManagerApi.Migrations
{
    [DbContext(typeof(SatelliteContext))]
    [Migration("20191029185338_dropIdAndSetFingerPrintAsKey")]
    partial class dropIdAndSetFingerPrintAsKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TMManagerApi.Models.OnlineSatellite", b =>
                {
                    b.Property<string>("Fingerprint")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account");

                    b.Property<bool>("IsDualMeter");

                    b.Property<bool>("IsOnline");

                    b.Property<DateTime>("LastSynch");

                    b.Property<string>("Meter");

                    b.Property<string>("OS");

                    b.Property<string>("Printer");

                    b.Property<string>("RemoteServiceVersion");

                    b.Property<string>("TeamViewerID");

                    b.Property<string>("TeamViewerVersion");

                    b.Property<string>("Truck");

                    b.Property<string>("TruckMasterVersion");

                    b.HasKey("Fingerprint");

                    b.ToTable("Satellites");
                });
#pragma warning restore 612, 618
        }
    }
}
